name: Grateful
options:
  bundleIdPrefix: com.sebastiandoyle
  deploymentTarget:
    iOS: "17.0"
targets:
  Grateful:
    type: application
    platform: iOS
    sources:
      - path: Grateful
      - path: Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sebastiandoyle.grateful
        PRODUCT_NAME: Grateful
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 2
        DEVELOPMENT_TEAM: 7277AB8379
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SUPPORTED_DESTINATIONS: "iPhone, iPad"
        SWIFT_VERSION: "5.0"
